// skill-ingest upserts the committed skills corpus (skills_seed.json, generated by
// app-site's server/cmd/skillgen) into the openpaths Postgres `skills` table. It is
// idempotent (ON CONFLICT(slug) DO UPDATE) and dry-run by default; pass -execute to
// write. The gateway's in-memory semantic index picks up the rows on next restart;
// ILIKE search serves them immediately.
//
//	go run ./cmd/skill-ingest -config config.yaml -execute
package main

import (
	"context"
	_ "embed"
	"encoding/json"
	"flag"
	"log"
	"os"

	"github.com/google/uuid"
	"github.com/joho/godotenv"

	"github.com/openpaths/openpaths/internal/config"
	"github.com/openpaths/openpaths/internal/db"
	"github.com/openpaths/openpaths/internal/db/migrations"
	"github.com/openpaths/openpaths/internal/db/queries"
	"github.com/openpaths/openpaths/internal/model"
)

//go:embed skills_seed.json
var skillsSeedJSON []byte

func main() {
	configPath := flag.String("config", "config.yaml", "path to OpenPaths config.yaml")
	file := flag.String("file", "", "path to skills_seed.json (defaults to the embedded corpus)")
	execute := flag.Bool("execute", false, "actually upsert; without this flag the script is a dry run")
	flag.Parse()

	raw := skillsSeedJSON
	if *file != "" {
		var err error
		raw, err = os.ReadFile(*file)
		if err != nil {
			log.Fatalf("read %s: %v", *file, err)
		}
	}
	var skills []model.Skill
	if err := json.Unmarshal(raw, &skills); err != nil {
		log.Fatalf("parse corpus: %v", err)
	}
	log.Printf("corpus: %d skills", len(skills))
	if !*execute {
		log.Printf("dry run (pass -execute to write). first slug: %s", firstSlug(skills))
		return
	}

	_ = godotenv.Load()
	cfg, err := config.Load(*configPath)
	if err != nil {
		log.Fatalf("load config: %v", err)
	}
	ctx := context.Background()
	database, err := db.New(ctx, cfg.Database)
	if err != nil {
		log.Fatalf("db: %v", err)
	}
	defer database.Close()
	if err := migrations.Run(ctx, database.Pool); err != nil {
		log.Fatalf("migrations: %v", err)
	}

	q := queries.NewSkillQueries(database.Pool)
	n := 0
	for i := range skills {
		s := skills[i]
		if s.ID == "" {
			s.ID = uuid.NewString()
		}
		if err := q.Upsert(ctx, &s); err != nil {
			log.Fatalf("upsert %s: %v", s.Slug, err)
		}
		n++
	}
	log.Printf("upserted %d skills", n)
}

func firstSlug(s []model.Skill) string {
	if len(s) == 0 {
		return "(none)"
	}
	return s[0].Slug
}
